categories = {
    {
  "Mortality Rates": [
    "Birth rate, crude (per 1,000 people)",
    "Death rate, crude (per 1,000 people)",
    "Mortality rate, adult, female (per 1,000 female adults)",
    "Mortality rate, adult, male (per 1,000 male adults)",
    "Mortality rate, infant (per 1,000 live births)",
    "Mortality rate, infant, female (per 1,000 live births)",
    "Mortality rate, infant, male (per 1,000 live births)",
    "Mortality rate, neonatal (per 1,000 live births)",
    "Mortality rate, under-5 (per 1,000 live births)",
    "Mortality rate, under-5, female (per 1,000 live births)",
    "Mortality rate, under-5, male (per 1,000 live births)",
    "Mortality caused by road traffic injury (per 100,000 population)",
    "Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)",
    "Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)",
    "Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)",
    "Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)",
    "Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)",
    "Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)",
    "Mortality rate attributed to unintentional poisoning (per 100,000 population)",
    "Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)",
    "Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)",
    "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)",
    "Number of infant deaths",
    "Number of infant deaths, female",
    "Number of infant deaths, male",
    "Number of maternal deaths",
    "Number of neonatal deaths",
    "Number of stillbirths",
    "Number of under-five deaths",
    "Number of under-five deaths, female",
    "Number of under-five deaths, male",
    "Stillbirth rate (per 1,000 total births)",
    "Suicide mortality rate (per 100,000 population)",
    "Suicide mortality rate, female (per 100,000 female population)",
    "Suicide mortality rate, male (per 100,000 male population)"
  ],
  
  "Maternal and Child Health": [
    "Adolescent fertility rate (births per 1,000 women ages 15-19)",
    "ARI treatment (% of children under 5 taken to a health provider)",
    "Births attended by skilled health staff (% of total)",
    "Children with fever receiving antimalarial drugs (% of children under age 5 with fever)",
    "Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)",
    "Diarrhea treatment (% of children under 5 who received ORS packet)",
    "Exclusive breastfeeding (% of children under 6 months)",
    "Fertility rate, total (births per woman)",
    "Immunization, DPT (% of children ages 12-23 months)",
    "Immunization, HepB3 (% of one-year-old children)",
    "Immunization, measles (% of children ages 12-23 months)",
    "Immunization, measles second dose (% of children by the nationally recommended age)",
    "Lifetime risk of maternal death (%)",
    "Lifetime risk of maternal death (1 in: rate varies by country)",
    "Low-birthweight babies (% of births)",
    "Maternal mortality ratio (modeled estimate, per 100,000 live births)",
    "Maternal mortality ratio (national estimate, per 100,000 live births)",
    "Newborns protected against tetanus (%)",
    "Pregnant women receiving prenatal care (%)",
    "Prevalence of anemia among children (% of children ages 6-59 months)",
    "Prevalence of anemia among pregnant women (%)",
    "Prevalence of overweight (modeled estimate, % of children under 5)",
    "Prevalence of overweight, weight for height (% of children under 5)",
    "Prevalence of overweight, weight for height, female (% of children under 5)",
    "Prevalence of overweight, weight for height, male (% of children under 5)",
    "Prevalence of severe wasting, weight for height (% of children under 5)",
    "Prevalence of severe wasting, weight for height, female (% of children under 5)",
    "Prevalence of severe wasting, weight for height, male (% of children under 5)",
    "Prevalence of stunting, height for age (% of children under 5)",
    "Prevalence of stunting, height for age (modeled estimate, % of children under 5)",
    "Prevalence of stunting, height for age, female (% of children under 5)",
    "Prevalence of stunting, height for age, male (% of children under 5)",
    "Prevalence of underweight, weight for age (% of children under 5)",
    "Prevalence of underweight, weight for age, female (% of children under 5)",
    "Prevalence of underweight, weight for age, male (% of children under 5)",
    "Prevalence of wasting, weight for height (% of children under 5)",
    "Prevalence of wasting, weight for height, female (% of children under 5)",
    "Prevalence of wasting, weight for height, male (% of children under 5)",
    "Teenage mothers (% of women ages 15-19 who have had children or are currently pregnant)",
    "Wanted fertility rate (births per woman)",
    "Women who were first married by age 15 (% of women ages 20-24)",
    "Women who were first married by age 18 (% of women ages 20-24)"
  ],
  
  "Infectious Diseases": [
    "Adults (ages 15+) and children (ages 0-14) newly infected with HIV",
    "Adults (ages 15-49) newly infected with HIV",
    "Antiretroviral therapy coverage (% of people living with HIV)",
    "Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",
    "Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)",
    "Incidence of HIV, ages 15-24, male (per 1,000 uninfected male population ages 15-24)",
    "Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)",
    "Incidence of HIV, ages 50+ (per 1,000 uninfected population ages 50+)",
    "Incidence of HIV, all (per 1,000 uninfected population)",
    "Incidence of malaria (per 1,000 population at risk)",
    "Incidence of tuberculosis (per 100,000 people)",
    "Prevalence of HIV, female (% ages 15-24)",
    "Prevalence of HIV, male (% ages 15-24)",
    "Prevalence of HIV, total (% of population ages 15-49)",
    "Tuberculosis case detection rate (%, all forms)",
    "Tuberculosis treatment success rate (% of new cases)",
    "Use of insecticide-treated bed nets (% of under-5 population)",
    "Women's share of population ages 15+ living with HIV (%)",
    "Young people (ages 15-24) newly infected with HIV"
  ],
  
  "Health Expenditure": [
    "Current health expenditure (% of GDP)",
    "Current health expenditure per capita (current US$)",
    "Current health expenditure per capita, PPP (current international $)",
    "Domestic general government health expenditure (% of current health expenditure)",
    "Domestic general government health expenditure (% of GDP)",
    "Domestic general government health expenditure (% of general government expenditure)",
    "Domestic general government health expenditure per capita (current US$)",
    "Domestic general government health expenditure per capita, PPP (current international $)",
    "Domestic private health expenditure (% of current health expenditure)",
    "Domestic private health expenditure per capita (current US$)",
    "Domestic private health expenditure per capita, PPP (current international $)",
    "External health expenditure (% of current health expenditure)",
    "External health expenditure per capita (current US$)",
    "External health expenditure per capita, PPP (current international $)",
    "Increase in poverty gap at $1.90 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (% of poverty line)",
    "Increase in poverty gap at $1.90 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (USD)",
    "Increase in poverty gap at $3.10 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (% of poverty line)",
    "Increase in poverty gap at $3.10 ($ 2011 PPP) poverty line due to out-of-pocket health care expenditure (USD)",
    "Number of people pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure",
    "Number of people pushed below the $3.10 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure",
    "Number of people spending more than 10% of household consumption or income on out-of-pocket health care expenditure",
    "Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure",
    "Out-of-pocket expenditure (% of current health expenditure)",
    "Out-of-pocket expenditure per capita (current US$)",
    "Out-of-pocket expenditure per capita, PPP (current international $)",
    "Proportion of population pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed below the 60% median consumption poverty line by out-of-pocket health expenditure (%)",
    "Proportion of population pushed further below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed further below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed further below the 60% median consumption poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed or further pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed or further pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
    "Proportion of population pushed or further pushed below the 60% median consumption poverty line by out-of-pocket health expenditure (%)",
    "Proportion of population spending more than 10% of household consumption or income on out-of-pocket health care expenditure (%)",
    "Proportion of population spending more than 25% of household consumption or income on out-of-pocket health care expenditure (%)",
    "Risk of catastrophic expenditure for surgical care (% of people at risk)",
    "Risk of impoverishing expenditure for surgical care (% of people at risk)"
  ],
  
  "Healthcare Infrastructure and Services": [
    "Hospital beds (per 1,000 people)",
    "Nurses and midwives (per 1,000 people)",
    "Number of surgical procedures (per 100,000 population)",
    "Physicians (per 1,000 people)",
    "Specialist surgical workforce (per 100,000 population)",
    "UHC service coverage index"
  ],
  
  "Water, Sanitation and Hygiene": [
    "People practicing open defecation (% of population)",
    "People practicing open defecation, rural (% of rural population)",
    "People practicing open defecation, urban (% of urban population)",
    "People using at least basic drinking water services (% of population)",
    "People using at least basic drinking water services, rural (% of rural population)",
    "People using at least basic drinking water services, urban (% of urban population)",
    "People using at least basic sanitation services (% of population)",
    "People using at least basic sanitation services, rural (% of rural population)",
    "People using at least basic sanitation services, urban (% of urban population)",
    "People using safely managed drinking water services (% of population)",
    "People using safely managed drinking water services, rural (% of rural population)",
    "People using safely managed drinking water services, urban (% of urban population)",
    "People with basic handwashing facilities including soap and water (% of population)",
    "People with basic handwashing facilities including soap and water, rural (% of rural population)",
    "People with basic handwashing facilities including soap and water, urban (% of urban population)"
  ],
  
  "Non-communicable Diseases and Risk Factors": [
    "Cause of death, by non-communicable diseases (% of total)",
    "Diabetes prevalence (% of population ages 20 to 79)",
    "Prevalence of anemia among non-pregnant women (% of women ages 15-49)",
    "Prevalence of anemia among women of reproductive age (% of women ages 15-49)",
    "Prevalence of current tobacco use (% of adults)",
    "Prevalence of current tobacco use, females (% of female adults)",
    "Prevalence of current tobacco use, males (% of male adults)",
    "Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",
    "Total alcohol consumption per capita, female (liters of pure alcohol, projected estimates, female 15+ years of age)",
    "Total alcohol consumption per capita, male (liters of pure alcohol, projected estimates, male 15+ years of age)"
  ],
  
  "Nutrition and Food Security": [
    "Consumption of iodized salt (% of households)",
    "Prevalence of moderate or severe food insecurity in the population (%)",
    "Prevalence of severe food insecurity in the population (%)",
    "Prevalence of undernourishment (% of population)"
  ],
  
  "Demographic Indicators": [
    "Age dependency ratio (% of working-age population)",
    "Age dependency ratio, old (% of working-age population)",
    "Age dependency ratio, young (% of working-age population)",
    "International migrant stock (% of population)",
    "International migrant stock, total",
    "Life expectancy at birth, female (years)",
    "Life expectancy at birth, male (years)",
    "Life expectancy at birth, total (years)",
    "Net migration",
    "Population ages 0-14 (% of total population)",
    "Population ages 0-14, female",
    "Population ages 0-14, female (% of female population)",
    "Population ages 0-14, male",
    "Population ages 0-14, male (% of male population)",
    "Population ages 0-14, total",
    "Population ages 00-04, female (% of female population)",
    "Population ages 00-04, male (% of male population)",
    "Population ages 05-09, female (% of female population)",
    "Population ages 05-09, male (% of male population)",
    "Population ages 10-14, female (% of female population)",
    "Population ages 10-14, male (% of male population)",
    "Population ages 15-19, female (% of female population)",
    "Population ages 15-19, male (% of male population)",
    "Population ages 15-64 (% of total population)",
    "Population ages 15-64, female",
    "Population ages 15-64, female (% of female population)",
    "Population ages 15-64, male",
    "Population ages 15-64, male (% of male population)",
    "Population ages 15-64, total",
    "Population ages 20-24, female (% of female population)",
    "Population ages 20-24, male (% of male population)",
    "Population ages 25-29, female (% of female population)",
    "Population ages 25-29, male (% of male population)",
    "Population ages 30-34, female (% of female population)",
    "Population ages 30-34, male (% of male population)",
    "Population ages 35-39, female (% of female population)",
    "Population ages 35-39, male (% of male population)",
    "Population ages 40-44, female (% of female population)",
    "Population ages 40-44, male (% of male population)",
    "Population ages 45-49, female (% of female population)",
    "Population ages 45-49, male (% of male population)",
    "Population ages 50-54, female (% of female population)",
    "Population ages 50-54, male (% of male population)",
    "Population ages 55-59, female (% of female population)",
    "Population ages 55-59, male (% of male population)",
    "Population ages 60-64, female (% of female population)",
    "Population ages 60-64, male (% of male population)",
    "Population ages 65 and above (% of total population)",
    "Population ages 65 and above, female",
    "Population ages 65 and above, female (% of female population)",
    "Population ages 65 and above, male",
    "Population ages 65 and above, male (% of male population)",
    "Population ages 65 and above, total",
    "Population ages 65-69, female (% of female population)",
    "Population ages 65-69, male (% of male population)",
    "Population ages 70-74, female (% of female population)",
    "Population ages 70-74, male (% of male population)",
    "Population ages 75-79, female (% of female population)",
    "Population ages 75-79, male (% of male population)",
    "Population ages 80 and above, female",
    "Population ages 80 and above, female (% of female population)",
    "Population ages 80 and above, male (% of male population)",
    "Population growth (annual %)",
    "Population, female",
    "Population, female (% of total population)",
    "Population, male",
    "Population, male (% of total population)",
    "Population, total",
    "Refugee population by country or territory of asylum",
    "Refugee population by country or territory of origin",
    "Sex ratio at birth (male births per female births)",
    "Survival to age 65, female (% of cohort)",
    "Survival to age 65, male (% of cohort)"
  ],
  
  "Reproductive Health": [
    "Contraceptive prevalence, any method (% of married women ages 15-49)",
    "Contraceptive prevalence, any modern method (% of married women ages 15-49)",
    "Unmet need for contraception (% of married women ages 15-49)"
  ],
  
  "Civil Registration": [
    "Completeness of birth registration (%)",
    "Completeness of birth registration, female (%)",
    "Completeness of birth registration, male (%)",
    "Completeness of birth registration, rural (%)",
    "Completeness of birth registration, urban (%)",
    "Completeness of death registration with cause-of-death information (%)"
  ],
  
  "Injury and External Causes": [
    "Cause of death, by injury (% of total)"
  ],
    "Comparative Insights": [],
    "Key Indicator Highlights": []
}

def map_category(indicator_name):
    for category, indicators in categories.items():
        if indicator_name in indicators:
            return category
    return "Other"